// Code generated by go generate DO NOT EDIT.

package main

// ItemIDs
func (xs Items) ItemIDs() []string {
	sli := make([]string, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].ItemID)
	}
	return sli
}
