// Code generated by "go-gen-slice-accessors"; DO NOT EDIT.
// Based on information from https://github.com/snamiki1212/go-gen-slice-accessors

package main

// CreatedAts
func (xs Importeds) CreatedAts() []any {
	sli := make([]any, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].CreatedAt)
	}
	return sli
}
