// Code generated by "go-gen-slice-accessors"; DO NOT EDIT.
// Based on information from https://github.com/snamiki1212/go-gen-slice-accessors

package main

import (
  "bytes"
  alias_time "time"
  "time"
)

// Buves
func (xs Imported2s) Buves() []bytes.Buffer {
	sli := make([]bytes.Buffer, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].Buf)
	}
	return sli
}

// CreatedAts
func (xs Imported2s) CreatedAts() []alias_time.Time {
	sli := make([]alias_time.Time, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].CreatedAt)
	}
	return sli
}

// UpdatedAts
func (xs Imported2s) UpdatedAts() []*time.Time {
	sli := make([]*time.Time, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].UpdatedAt)
	}
	return sli
}
