// Code generated by "go-gen-slice-accessors"; DO NOT EDIT.
// Based on information from https://github.com/snamiki1212/go-gen-slice-accessors

package main

import (
  "time"
)

// CreatedAts
func (xs Imported1s) CreatedAts() []time.Time {
	sli := make([]time.Time, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].CreatedAt)
	}
	return sli
}

// UpdatedAts
func (xs Imported1s) UpdatedAts() []*time.Time {
	sli := make([]*time.Time, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].UpdatedAt)
	}
	return sli
}
