// Code generated by go generate DO NOT EDIT.

package main

// GetAccountIDs
func (xs Accounts) GetAccountIDs() []string {
	sli := make([]string, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].AccountID)
	}
	return sli
}

// AgeList
func (xs Accounts) AgeList() []int64 {
	sli := make([]int64, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].Age)
	}
	return sli
}
